[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'benjie/neomake-local-eslint.vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
