export GOPATH=$HOME/go
export PATH=$HOME/bin:/opt/brew/bin:$PATH:$GOPATH/bin:/Users/makimoto/.cargo/bin

zstyle :compinstall filename '/Users/makimoto/.zshrc'
zstyle '*' single-ignored show

autoload -Uz colors; colors

autoload -Uz vcs_info
zstyle ':vcs_info:*' formats '|%b'
zstyle ':vcs_info:*' actionformats '|%b|%a'

precmd () {
  psvar=()
  vcs_info
  [[ -n "$vcs_info_msg_0_" ]] && psvar[1]="$vcs_info_msg_0_"
  PROMPT="[%.$psvar]%# "
}

setopt \
  always_last_prompt \
  append_history \
  auto_menu \
  auto_param_keys \
  auto_param_slash \
  auto_pushd \
  autocd \
  extended_glob \
  extended_history \
  hist_ignore_all_dups \
  hist_ignore_space \
  hist_reduce_blanks \
  magic_equal_subst \
  mark_dirs \
  menu_complete \
  no_beep \
  notify \
  pushd_ignore_dups \
  share_history \


bindkey -e

if [ -f "`which gpg-agent`" -a -f "`which gpg`" ];then
  pgrep -q gpg-agent || eval $(`brew --prefix`/bin/gpg-agent --daemon --write-env-file ${HOME}/.gpg-agent-info)
  [ -f ${HOME}/.gpg-agent-info ] && source ${HOME}/.gpg-agent-info
  export GPG_AGENT_INFO
  export GPG_TTY=`tty`
fi

for i in ${HOME}/.zsh.d/*.zsh
  source $i

if [ -f ${HOME}/.zshrc.local ];then
  source $HOME/.zshrc.local
fi
